name: Terraform Plan

on:
  pull_request:
    branches:
      - develop
    types:
      - labeled
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      if: github.event_name == 'pull_request' && contains(github.event.action, 'labeled') && github.event.pull_request.labels.*.name == 'plan' && github.event.pull_request.merged == false && github.event.pull_request.head.ref == 'develop' && github.event.pull_request.head.repo.full_name == github.repository
      run: terraform plan -out=tfplan
