name: Terraform Plan

on:
  pull_request:
    branches:
      - develop
    types:
      - labeled
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
